import type { Metadata } from "next";
import { Passion_One } from "next/font/google";
import "./globals.css";

const passionOne = Passion_One({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-passion-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={passionOne.className}>{children}</body>
    </html>
  );
}
